# Generated by Django 5.0.9 on 2024-11-12 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0623_merge_20241030_1835"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_privileged_user",
            field=models.BooleanField(default=False, help_text="Hide user from normal members"),
        ),
    ]
