# Generated by Django 5.0.9 on 2024-11-12 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0624_userprofile_is_privileged_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmuserdefault",
            name="is_privileged_user",
            field=models.BooleanField(default=False, help_text="Hide user from normal members"),
        ),
    ]
