# Generated by Django 5.0.9 on 2024-11-13 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0626_remove_realmuserdefault_is_privileged_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmuserdefault",
            name="is_privileged_user",
            field=models.BooleanField(default=False, help_text="Hide user from normal members"),
        ),
    ]
