# Generated by Django 5.0.9 on 2024-11-13 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0627_realmuserdefault_is_privileged_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="realmuserdefault",
            name="is_privileged_user",
        ),
    ]
