# Generated by Django 5.0.9 on 2024-11-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0628_remove_realmuserdefault_is_privileged_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_privileged_user",
            field=models.BooleanField(default=False, help_text="Hide user from normal members"),
        ),
    ]
