# Generated by Django 5.0.9 on 2024-11-19 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0629_userprofile_is_privileged_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="hide_user_panel_button",
            field=models.BooleanField(default=False),
        ),
    ]
