# Generated by Django 5.0.9 on 2024-12-04 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0630_realm_hide_user_panel_button"),
        ("zerver", "0635_alter_namedusergroup_can_remove_members_group"),
    ]

    operations = []
